spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.8:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 80

wechat:
  mpAppId: wxa4fb609e642696be
  mpAppSecret: 310ca42cb9f36f27a9c997b01faf6a0b
  openAppId:
  openAppSecret:
  mchId:
  mchKey:
  keyPath:
  notifyUrl: http://gzhennaxia.natapp1.cc/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://gzhennaxia.natapp1.cc
  wecharOpenAuthorize: http://gzhennaxia.natapp1.cc
  sell: